export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const LOADING_STARTED = "LOADING_STARTED";
export const LOADING_COMPLETED = "LOADING_COMPLETED";

export const CREATE_DECK_SUCCESS = "CREATE_DECK_SUCCESS";
export const CREATE_DECK_FAIL = "CREATE_DECK_FAIL";
export const GET_DECK_SUCCESS = "GET_DECK_SUCCESS";
export const GET_DECK_FAIL = "GET_DECK_FAIL";
export const GET_ALL_DECKS_SUCCESS = "GET_ALL_DECKS_SUCCESS";
export const GET_ALL_DECKS_FAIL = "GET_ALL_DECKS_FAIL";
export const PATCH_DECK_SUCCESS = "PATCH_DECK_SUCCESS";
export const PATCH_DECK_FAIL = "PATCH_DECK_FAIL";
export const DELETE_DECK_SUCCESS = "DELETE_DECK_SUCCESS";
export const DELETE_DECK_FAIL = "DELETE_DECK_FAIL";
export const GET_DECK_FROM_LIST = "GET_DECK_FROM_LIST";
export const SET_ACTIVE_DECK = "SET_ACTIVE_DECK";
